name: ManagePlugins
version: '${project.version}'
main: hedystia.core.ManagePlugins
api-version: 1.19
authors: [contact@zastinian.com]
description: Plugin Manager
website: hedystia.com
commands:
  manage_plugins:
    description: Manage Plugins
    usage: /manage_plugins <option> <plugin>
    aliases:
      - mgplug